language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://agxwerker.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "EIxBn7jQQh3ZLtIeEZySK/0Kf1PYGPPo//jAU0EI4lVZHANqa1DVKsaMH+g3nzNGt+PUxVTU6G2d7IPcE06o07U/Ad6uHXitpANOSp980F+Dj9xtpDd5agsPz7bbohDRnLf1Zi+bC7fcD+zn+r+oa538LYVfQHuPbxFS6Y0jxKLVmNQDn+yaLHIO77/CmhzNPN1M4DVPPFgLhDrfdnTnqjl81o8zCiWnQsn+zIZn823pirizjqagn/Jr8yEWAvaxqUcnkrRwCyAkh9wg37AVy9p5YF3btSBmMSWZ9zwzYpVWtzqCX6grqXjuBZbscycvZCC+bqvTwHd0uAI/HI6Jx42JfcAtZOYUDVs+6givULofMbwpRN0asYMGjK4CHXiMAyJejcxoi9D1Dsh4Z1rkHe6X83Lqlsck/VVZIca/Xns3HL1yO1PUnZ/UCqkGhlVP7ytnoUeKqJ7zF6liR4a1Kh0jnf+Uth9DT9Uv71rZSQC+D/cKYyKa31xMjL/lA3RBfWrjUXbK5704retddHaIIzQqf4O3qLM6CVDTlcka4eLv2u3U9yfmCzurXK9HB3REDxGTsPbW7XnColPVzxPxNmmHCeKWlVeuWkQKT4eP/omne+XkYRAWYcAqnjwKK6UyXyEezMmhCoF7E2c7PmgRGu6PYZSykU0T2gWIxS5FaYs="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
